CREATE TABLE IF NOT EXISTS body_size_data (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    size_name VARCHAR(50) NOT NULL,
    height DECIMAL(5,1),
    weight DECIMAL(5,1),
    shoulder_width DECIMAL(5,1),
    chest_circumference DECIMAL(5,1),
    waist_circumference DECIMAL(5,1),
    hip_circumference DECIMAL(5,1),
    neck_circumference DECIMAL(5,1),
    arm_length DECIMAL(5,1),
    sleeve_length DECIMAL(5,1),
    waist_length DECIMAL(5,1),
    inseam_length DECIMAL(5,1),
    body_type VARCHAR(20),
    gender INT DEFAULT 1,
    is_default INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted INT DEFAULT 0
);