apiVersion: v1
kind: Service
metadata:
  name: ai
  namespace: tailor-is-prod
  labels:
    app: ai
    app.kubernetes.io/name: tailor-is-ai
spec:
  type: ClusterIP
  selector:
    app: ai
  ports:
    - name: http
      port: 8106
      targetPort: 8106
      protocol: TCP
