apiVersion: v1
kind: Service
metadata:
  name: copyright
  namespace: tailor-is-prod
  labels:
    app: copyright
    app.kubernetes.io/name: tailor-is-copyright
spec:
  type: ClusterIP
  selector:
    app: copyright
  ports:
    - name: http
      port: 8107
      targetPort: 8107
      protocol: TCP
