apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: tailor-is-prod
  labels:
    app: order
    app.kubernetes.io/name: tailor-is-order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: http
      port: 8103
      targetPort: 8103
      protocol: TCP
